language: python
# python 3.4 fails for now because of gevents dependencies, which cannot be installed via pip
python:
  - "3.4"
  - "3.3"
  - "2.7"


before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran graphviz


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install numpy pyparsing matplotlib 
  - pip install nose coverage
  - pip install bioservices
  - pip install biokit

# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py nosetests  --with-coverage --cover-package cellnopt --logging-level ERROR --attr '!skip_travis'
    
after_success:
  coveralls
