language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5



before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=$HOME/miniconda/bin:$PATH
  - export PATH=$HOME/miniconda2/bin:$PATH
  - hash -r
  - conda update --yes conda
  # This help testing code with pylab
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - conda install --yes numpy matplotlib scipy networkx pandas>=0.15 graphviz
  - pip install pulp numexpr wrapt bottleneck  
  - pip install nose coverage
  - pip install bioservices
  - pip install biokit 
  - pip install pygraphviz



# # command to run tests, e.g. python setup.py test
script:  
  - python setup.py nosetests  --with-coverage --cover-package cno --logging-level ERROR --attr '!skip_travis'
    
after_success:
  coveralls
